### ISSUE TITLE
How to duplicate associations related to the record is being duplicated?

### ISSUE THREAD

**Issue by habibaz** [zorab47/active_admin-duplicatable#4]
In my current structure, I have 3 has many association with the model I want to duplicate. How to I make sure the has many associations and their nested associations are getting duplicate as well?

Really appreciate a quick reply.

**Comment by zorab47** [comment]
Depends on how you implement duplication. I've used [Amoeba](https://github.com/rocksolidwebdesign/amoeba) gem to make it easier to copy dependent records.
